# Generated by Django 4.2 on 2023-04-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolverequest',
            name='evolved_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='evolverequest',
            name='finished_generating',
            field=models.DateTimeField(null=True),
        ),
    ]
