# Generated by Django 4.2 on 2023-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0002_evolverequest_evolved_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolverequest',
            name='object',
            field=models.CharField(choices=[('EvolveObject.RECTANGLE', 'Rectangle'), ('EvolveObject.CIRCLE', 'Circle'), ('EvolveObject.EMOJI', 'Emoji')], default='EvolveObject.RECTANGLE', max_length=120),
        ),
        migrations.AlterField(
            model_name='evolverequest',
            name='evolved_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evolverequest',
            name='finished_generating',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
